//INCLUDE MENU HELPER CLASS
//INCLUDE VALIDATION HELPER CLASS
//git test
int main()
{
	//TODO: PRINT START MENU ASKING IF USER WANTS TO PLAY
		//TODO: VALIDATE INPUT
	//TODO: WHILE USER WANTS TO PLAY
		//TODO: ASK USER IF THEY WANT TO SET STRENGTH OF TOOLS
			//TODO: VALIDATE INPUT 
				//TODO: IF YES CALL RPSGAME SETSTRENGTH FUNCTION
		//TODO: PRINT MENU WITH ROCK, PAPER SCISSORS
			//TODO:GET AND VALIDATE INPUT
				//TODO: PASS TO RPSGAME SETHUMANTOOL FUNCTION
		//TODO: CALL SETCOMPUTER TOOL
		//TODO: CALL RUNGAME
		//TODO: PRINT RESULTS OF ROUND
		//TODO: CALL RPSGAME CLEANUP FUNCTION
		//TODO: PRINT START MENU AGAIN ASKING IF USER WANTS TO CONTINUE PLAYING
			//TODO: IF YES, GO BACK TO SETTING STRENGTH OF TOOLS
			//TODO: IF NO, EXIT
	return 0;
}
