#include "RPSGame.h"

RPSGame::RPSGame()
{
	human = 0;
	computer = 0;
	human_wins = 0;
	computer_wins = 0;
	ties = 0;
	sstrength = 1;
	pstrength = 1;
	rstrength = 1;
}

char RPSGame::AI()
{
	//TODO: USE VECTOR OF PAST HUMAN CHOICES TO DETERMINE BEST MOVE FOR COMPUTER
}

void RPSGame::printStats()
{
	//TODO: PRINT ALL DETAILS OF CURRENT ROUND
}

void RPSGame::setStrength()
{
	//TODO: PROMPT USE FOR SPECIFIC STRENGTH AND SET THEM TO MEMBER VARIABLES
	//TODO: VALIDATE INPUT
	//TODO: STRENGTHS USED WITH NEW OBJECT CONSTRUCTOR
}

void RPSGame::setHumanTool(char)
{
	//TODO: SET HUMAN POINTER TO DYNAMICALLY ALLOCATED S, R OR P OBJECT
	//TODO: PASS APPROPRAITE STRENGTH IN CONSTRUCTOR
}

void RPSGame::setComputerTool(char)
{
	//TODO: SET COMPUTER POINTER TO DYNAMICALLY ALLOCATED S, R OR P OBJECT
	//TODO: PASS APPROPRAITE STRENGTH IN CONSTRUCTOR
}


void RPSGame::runGame()
{
	//TODO: CALL COMPUTER AND HUMAN FIGHT FUNCTIONS
	//TODO: COMPARE RESULTS RETURNED FROM FUNCTIONS
	//TODO: ADD RESULT TO MEMBER VARIABLES
}

void RPSGame::cleanUp()
{
	//TODO: DELETE DYNAMIC MEMORY AFTER EACH ROUND
	//TODO: ADD HUMAN CHOICE TO VECTOR
}

RPSGame::~RPSGame()
{
}
